apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: loan-approval-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/PINJALA780/loan-approval-mlops.git
    targetRevision: HEAD
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
